"""add_uti_and_bed_to_patients

Revision ID: 7b798d5e9fbd
Revises: bc5d5f2eb432
Create Date: 2026-08-06 15:19:20.074194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b798d5e9fbd'
down_revision: Union[str, Sequence[str], None] = 'bc5d5f2eb432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('uti', sa.String(length=50), server_default='UTI 1', nullable=False))
    op.alter_column('patients', 'bed',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('patients', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_patients_uti'), 'patients', ['uti'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_uti'), table_name='patients')
    op.alter_column('patients', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('patients', 'bed',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('patients', 'uti')
    # ### end Alembic commands ###
