"""add_qualitative_value_and_update_volume_ml

Revision ID: bc5d5f2eb432
Revises: 
Create Date: 2026-08-06 09:27:25.721280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc5d5f2eb432'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('fluid_records', sa.Column('qualitative_value', sa.String(length=50), nullable=True))
    op.execute("UPDATE fluid_records SET qualitative_value = volume_ml::text WHERE volume_ml::text ~ '^\\+'")
    op.alter_column('fluid_records', 'volume_ml',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Float(),
               nullable=True,
               postgresql_using="CASE WHEN volume_ml::text ~ '^[0-9.]+$' THEN volume_ml::numeric ELSE NULL END")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('fluid_records', 'volume_ml',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_column('fluid_records', 'qualitative_value')
    # ### end Alembic commands ###
