"""add_username_to_user

Revision ID: f4a1caa61952
Revises: 4af2cd1b951d
Create Date: 2026-08-10 15:45:55.842502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4a1caa61952'
down_revision: Union[str, Sequence[str], None] = '4af2cd1b951d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable
    op.add_column('users', sa.Column('username', sa.String(length=60), nullable=True))
    
    # 2. Backfill with deduplication
    bind = op.get_bind()
    users = bind.execute(sa.text("SELECT id, email FROM users ORDER BY id")).fetchall()
    
    used_usernames = set()
    for user_id, email in users:
        base_username = email.split('@')[0].lower()
        username = base_username
        suffix = 2
        while username in used_usernames:
            username = f"{base_username}{suffix}"
            suffix += 1
        used_usernames.add(username)
        
        bind.execute(
            sa.text("UPDATE users SET username = :username WHERE id = :id"),
            {"username": username, "id": user_id}
        )
        
    # 3. Alter to NOT NULL
    op.alter_column('users', 'username', existing_type=sa.String(length=60), nullable=False)
    
    # 4. Add unique index
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
